name: Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: CMake generate debug
        run: cmake -B build-debug -S . -DCMAKE_BUILD_TYPE=Debug
      - name: CMake generate release
        run: cmake -B build-release -S . -DCMAKE_BUILD_TYPE=Release
      - name: CMake build debug
        run: cmake --build build-debug -j
      - name: CMake build release
        run: cmake --build build-release -j
